### ISSUE TITLE
Getting TRSpec working with `asdf`

### ISSUE THREAD

**Issue by aardvarkk** [astrauka/TestRSpec#43] opened 2019-10-08 20:00 UTC
I had trouble getting the asdf package manager working with TestRSpec. Eventually I realized that the `PATH` env var that Sublime was supplying was incorrect. Normally, you want the `~/.asdf/shims` path *ahead* of things like the System Ruby. However, Sublime had it inverted so the System Ruby was preferred over the ASDF version. I ended up adding the following to the config and now things seem to work as expected:

```
  "rspec_add_to_path": "~/.asdf/shims",
```

**Comment by OlegSmelov** [comment] 2019-10-09 10:41
Which OS do you use? I remember having to install https://packagecontrol.io/packages/Fix%20Mac%20Path to use your shell's environment, but then Sublime included a fix for this by default. Do you have this plugin installed?

(Slightly offtopic) I've never used ASDF, is there any benefit over `rbenv`, `pyenv` and others?

**Comment by aardvarkk** [comment] 2019-10-09 17:07
I'm using macOS. I hadn't heard of that package, but I'll try it out to see if it fixes my problem! Great suggestion.

I switched to asdf because it has support for a wider variety of languages/frameworks. I started working on an elixir/erlang project and wanted to use a consistent tool between everything. asdf supported both ruby installs and also elixir/erlang in a fairly simple setup that was quick to learn. asdf has plugins for a whole bunch of languages, and it's just a simple CLI tool that doesn't do anything too surprising. I was just using chruby + ruby-install before, so it wasn't a huge change for me. I'm happy with it so far now that it's set up.

I'll update you about the PATH fix in a second here...

**Comment by aardvarkk** [comment] 2019-10-09 17:12
I tried the Fix Mac Path package (and quit Sublime and re-entered) and it didn't seem to fix the problem. It looks like the only fix I've found so far is to manually add the shims to the PATH in the package settings as I've done. Appreciate the idea, though, thanks!

**Comment by OlegSmelov** [comment] 2019-10-09 21:09
I've just installed asdf and could not reproduce this.

If I had to guess, I'd say you're missing `. $HOME/.asdf/asdf.sh` in your `~/.bash_profile`.

**Comment by aardvarkk** [comment] 2019-10-09 21:13
What's weird is that the PATH debug info that prints into the Sublime console when it fails *does* show the asdf paths, they just come *after* /usr/local/bin and so on. So the shims aren't used. Very confusing!

**Comment by OlegSmelov** [comment] 2019-10-09 21:19
The plugin uses Sublime's `window.run_command` internally, which runs `bash` as far as I can tell.

If you want to debug this issue some more:

```python
# run in Sublime console (ctrl+`)
window.run_command("exec", {"shell_cmd": "echo $0; echo $PATH; which ruby; ruby --version"})
```

But I still believe fixing this comes down to making asdf work in bash.

**Comment by aardvarkk** [comment] 2019-10-09 23:15
Beautiful! Indeed, once I ran the asdf bash setup (in *addition* to the zsh setup), everything went fine. That involved running the following commands:

```
echo -e "\n. $(brew --prefix asdf)/asdf.sh" >> ~/.bash_profile
echo -e "\n. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash" >> ~/.bash_profile
```

Basically just adding some scripts to the bash profile. I think my confusion was compounded by the fact that macOS Catalina *just* switched the default terminal to `zsh` from `bash`, but Sublime is still using `bash`, so that threw me for a bit of a loop. Really appreciate the help! I was looking for this issue to act more like documentation than an actual complaint about TestRSpec. Glad it's all working now, thanks again!

**Comment by OlegSmelov** [comment] 2019-10-10 07:13
I was hesitant to include `rspec_add_to_path` override because something felt off - `rbenv` doesn't require it, so I figured `asdf` should work similarly. I'm glad we found the root cause of the problem. :smile: 

I wouldn't be surprised if Sublime switches to `zsh` by default in the future.

**Closed by OlegSmelov** 2019-10-10 07:13 UTC

**Comment by joshmfrankel** [comment] 2023-10-24 13:14
The following worked for me with Mac OSX (Sonoma) while running zsh not installed via brew. :-) 

```
# ~/.bash_profile
. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
```
